- 👋 Hi, I’m @ManuelAlcantar120
- 👀 I’m interested in efficient coding and AI
- 🌱 I’m currently learning AI
- 💞️ I’m looking to collaborate on various projects about AI and software development
- 📫 How to reach me ... Business mail -> mdac210@gmail.com
